version: '3'

services:

  management-portal-api:
    build:
      context: ./
      dockerfile: .management-api.Dockerfile
    env_file:
      - ./.env
    depends_on:
      - management-portal-pg-db
    working_dir: /app
    ports:
      - '3001:3001'
    container_name: management-portal-api
    volumes:
      - ./:/app 
      - management-portal-api-node_modules:/app/node_modules
    networks:
      - management-portal_network

  management-portal-pg-db:
    image: postgres:15.2-alpine
    ports:
      - '5007:5432'
    environment:
      POSTGRES_USER: julian
      POSTGRES_PASSWORD: password
      POSTGRES_DB: management-portal-pg-db
    container_name: management-portal-pg-db
    volumes:
      - management-portal-db-data:/var/lib/postgresql/data
    networks:
      - management-portal_network

volumes:
  management-portal-api-node_modules:
  management-portal-db-data:

networks:
  management-portal_network:


  